<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FamilyTree.Infrastructure\FamilyTree.Infrastructure.csproj" />
    <ProjectReference Include="..\FamilyTree.Application\FamilyTree.Application.csproj" />
    <ProjectReference Include="..\FamilyTree.Contracts\FamilyTree.Contracts.csproj" />
    <ProjectReference Include="..\FamilyTree.Domain\FamilyTree.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

</Project>
