namespace FamilyTree.Infrastructure.Persistence.Seed;

/// <summary>
/// Every ISO 3166-1 alpha-2 country and inhabited territory, with its E.164 dialing code.
/// Uninhabited territories (Antarctica, Bouvet Island, the Heard and McDonald Islands and the
/// like) are omitted: nobody resides there, so they would be noise in a country-of-residence
/// picker.
///
/// Names are CLDR's, generated once rather than fetched, so the list cannot drift at runtime
/// and needs no external service. Three are overridden by hand — CLDR calls PS "الأراضي
/// الفلسطينية / Palestinian Territories", which is not what this family calls home, and gives
/// SA and AE their formal long names where the short ones read better in a dropdown.
///
/// Note that DialCode is NOT unique — +1 covers the US, Canada and much of the Caribbean, and
/// +44 covers the UK, Jersey, Guernsey and the Isle of Man. Only Code is unique.
///
/// Regenerate with tools/generate-country-catalog.cjs. Adding a country by hand is fine too:
/// the seeder inserts only codes the database does not already have, so it stays idempotent.
/// </summary>
public static class CountryCatalog
{
    public static IReadOnlyList<(string Code, string NameAr, string NameEn, string DialCode)> All { get; } =
    [
        ("AD", "أندورا", "Andorra", "+376"),
        ("AE", "الإمارات", "United Arab Emirates", "+971"),
        ("AF", "أفغانستان", "Afghanistan", "+93"),
        ("AG", "أنتيغوا وبربودا", "Antigua & Barbuda", "+1268"),
        ("AI", "أنغويلا", "Anguilla", "+1264"),
        ("AL", "ألبانيا", "Albania", "+355"),
        ("AM", "أرمينيا", "Armenia", "+374"),
        ("AO", "أنغولا", "Angola", "+244"),
        ("AR", "الأرجنتين", "Argentina", "+54"),
        ("AS", "ساموا الأمريكية", "American Samoa", "+1684"),
        ("AT", "النمسا", "Austria", "+43"),
        ("AU", "أستراليا", "Australia", "+61"),
        ("AW", "أروبا", "Aruba", "+297"),
        ("AX", "جزر آلاند", "Åland Islands", "+358"),
        ("AZ", "أذربيجان", "Azerbaijan", "+994"),
        ("BA", "البوسنة والهرسك", "Bosnia & Herzegovina", "+387"),
        ("BB", "بربادوس", "Barbados", "+1246"),
        ("BD", "بنغلاديش", "Bangladesh", "+880"),
        ("BE", "بلجيكا", "Belgium", "+32"),
        ("BF", "بوركينا فاسو", "Burkina Faso", "+226"),
        ("BG", "بلغاريا", "Bulgaria", "+359"),
        ("BH", "البحرين", "Bahrain", "+973"),
        ("BI", "بوروندي", "Burundi", "+257"),
        ("BJ", "بنين", "Benin", "+229"),
        ("BL", "سان بارتليمي", "St. Barthélemy", "+590"),
        ("BM", "برمودا", "Bermuda", "+1441"),
        ("BN", "بروناي", "Brunei", "+673"),
        ("BO", "بوليفيا", "Bolivia", "+591"),
        ("BQ", "هولندا الكاريبية", "Caribbean Netherlands", "+599"),
        ("BR", "البرازيل", "Brazil", "+55"),
        ("BS", "جزر البهاما", "Bahamas", "+1242"),
        ("BT", "بوتان", "Bhutan", "+975"),
        ("BW", "بوتسوانا", "Botswana", "+267"),
        ("BY", "بيلاروس", "Belarus", "+375"),
        ("BZ", "بليز", "Belize", "+501"),
        ("CA", "كندا", "Canada", "+1"),
        ("CD", "الكونغو - كينشاسا", "Congo - Kinshasa", "+243"),
        ("CF", "جمهورية أفريقيا الوسطى", "Central African Republic", "+236"),
        ("CG", "الكونغو - برازافيل", "Congo - Brazzaville", "+242"),
        ("CH", "سويسرا", "Switzerland", "+41"),
        ("CI", "ساحل العاج", "Côte d’Ivoire", "+225"),
        ("CK", "جزر كوك", "Cook Islands", "+682"),
        ("CL", "تشيلي", "Chile", "+56"),
        ("CM", "الكاميرون", "Cameroon", "+237"),
        ("CN", "الصين", "China", "+86"),
        ("CO", "كولومبيا", "Colombia", "+57"),
        ("CR", "كوستاريكا", "Costa Rica", "+506"),
        ("CU", "كوبا", "Cuba", "+53"),
        ("CV", "الرأس الأخضر", "Cape Verde", "+238"),
        ("CW", "كوراساو", "Curaçao", "+599"),
        ("CY", "قبرص", "Cyprus", "+357"),
        ("CZ", "التشيك", "Czechia", "+420"),
        ("DE", "ألمانيا", "Germany", "+49"),
        ("DJ", "جيبوتي", "Djibouti", "+253"),
        ("DK", "الدانمرك", "Denmark", "+45"),
        ("DM", "دومينيكا", "Dominica", "+1767"),
        ("DO", "جمهورية الدومينيكان", "Dominican Republic", "+1809"),
        ("DZ", "الجزائر", "Algeria", "+213"),
        ("EC", "الإكوادور", "Ecuador", "+593"),
        ("EE", "إستونيا", "Estonia", "+372"),
        ("EG", "مصر", "Egypt", "+20"),
        ("EH", "الصحراء الغربية", "Western Sahara", "+212"),
        ("ER", "إريتريا", "Eritrea", "+291"),
        ("ES", "إسبانيا", "Spain", "+34"),
        ("ET", "إثيوبيا", "Ethiopia", "+251"),
        ("FI", "فنلندا", "Finland", "+358"),
        ("FJ", "فيجي", "Fiji", "+679"),
        ("FK", "جزر فوكلاند", "Falkland Islands", "+500"),
        ("FM", "ميكرونيزيا", "Micronesia", "+691"),
        ("FO", "جزر فارو", "Faroe Islands", "+298"),
        ("FR", "فرنسا", "France", "+33"),
        ("GA", "الغابون", "Gabon", "+241"),
        ("GB", "المملكة المتحدة", "United Kingdom", "+44"),
        ("GD", "غرينادا", "Grenada", "+1473"),
        ("GE", "جورجيا", "Georgia", "+995"),
        ("GF", "غويانا الفرنسية", "French Guiana", "+594"),
        ("GG", "غيرنزي", "Guernsey", "+44"),
        ("GH", "غانا", "Ghana", "+233"),
        ("GI", "جبل طارق", "Gibraltar", "+350"),
        ("GL", "غرينلاند", "Greenland", "+299"),
        ("GM", "غامبيا", "Gambia", "+220"),
        ("GN", "غينيا", "Guinea", "+224"),
        ("GP", "غوادلوب", "Guadeloupe", "+590"),
        ("GQ", "غينيا الاستوائية", "Equatorial Guinea", "+240"),
        ("GR", "اليونان", "Greece", "+30"),
        ("GT", "غواتيمالا", "Guatemala", "+502"),
        ("GU", "غوام", "Guam", "+1671"),
        ("GW", "غينيا بيساو", "Guinea-Bissau", "+245"),
        ("GY", "غيانا", "Guyana", "+592"),
        ("HK", "هونغ كونغ الصينية (منطقة إدارية خاصة)", "Hong Kong SAR China", "+852"),
        ("HN", "هندوراس", "Honduras", "+504"),
        ("HR", "كرواتيا", "Croatia", "+385"),
        ("HT", "هايتي", "Haiti", "+509"),
        ("HU", "هنغاريا", "Hungary", "+36"),
        ("ID", "إندونيسيا", "Indonesia", "+62"),
        ("IE", "أيرلندا", "Ireland", "+353"),
        ("IL", "إسرائيل", "Israel", "+972"),
        ("IM", "جزيرة مان", "Isle of Man", "+44"),
        ("IN", "الهند", "India", "+91"),
        ("IQ", "العراق", "Iraq", "+964"),
        ("IR", "إيران", "Iran", "+98"),
        ("IS", "آيسلندا", "Iceland", "+354"),
        ("IT", "إيطاليا", "Italy", "+39"),
        ("JE", "جيرسي", "Jersey", "+44"),
        ("JM", "جامايكا", "Jamaica", "+1876"),
        ("JO", "الأردن", "Jordan", "+962"),
        ("JP", "اليابان", "Japan", "+81"),
        ("KE", "كينيا", "Kenya", "+254"),
        ("KG", "قيرغيزستان", "Kyrgyzstan", "+996"),
        ("KH", "كمبوديا", "Cambodia", "+855"),
        ("KI", "كيريباتي", "Kiribati", "+686"),
        ("KM", "جزر القمر", "Comoros", "+269"),
        ("KN", "سانت كيتس ونيفيس", "St. Kitts & Nevis", "+1869"),
        ("KP", "كوريا الشمالية", "North Korea", "+850"),
        ("KR", "كوريا الجنوبية", "South Korea", "+82"),
        ("KW", "الكويت", "Kuwait", "+965"),
        ("KY", "جزر كايمان", "Cayman Islands", "+1345"),
        ("KZ", "كازاخستان", "Kazakhstan", "+7"),
        ("LA", "لاوس", "Laos", "+856"),
        ("LB", "لبنان", "Lebanon", "+961"),
        ("LC", "سانت لوسيا", "St. Lucia", "+1758"),
        ("LI", "ليختنشتاين", "Liechtenstein", "+423"),
        ("LK", "سريلانكا", "Sri Lanka", "+94"),
        ("LR", "ليبيريا", "Liberia", "+231"),
        ("LS", "ليسوتو", "Lesotho", "+266"),
        ("LT", "ليتوانيا", "Lithuania", "+370"),
        ("LU", "لوكسمبورغ", "Luxembourg", "+352"),
        ("LV", "لاتفيا", "Latvia", "+371"),
        ("LY", "ليبيا", "Libya", "+218"),
        ("MA", "المغرب", "Morocco", "+212"),
        ("MC", "موناكو", "Monaco", "+377"),
        ("MD", "مولدوفا", "Moldova", "+373"),
        ("ME", "الجبل الأسود", "Montenegro", "+382"),
        ("MF", "سان مارتن", "St. Martin", "+590"),
        ("MG", "مدغشقر", "Madagascar", "+261"),
        ("MH", "جزر مارشال", "Marshall Islands", "+692"),
        ("MK", "مقدونيا الشمالية", "North Macedonia", "+389"),
        ("ML", "مالي", "Mali", "+223"),
        ("MM", "ميانمار (بورما)", "Myanmar (Burma)", "+95"),
        ("MN", "منغوليا", "Mongolia", "+976"),
        ("MO", "منطقة ماكاو الإدارية الخاصة", "Macao SAR China", "+853"),
        ("MP", "جزر ماريانا الشمالية", "Northern Mariana Islands", "+1670"),
        ("MQ", "جزر المارتينيك", "Martinique", "+596"),
        ("MR", "موريتانيا", "Mauritania", "+222"),
        ("MS", "مونتسرات", "Montserrat", "+1664"),
        ("MT", "مالطا", "Malta", "+356"),
        ("MU", "موريشيوس", "Mauritius", "+230"),
        ("MV", "جزر المالديف", "Maldives", "+960"),
        ("MW", "ملاوي", "Malawi", "+265"),
        ("MX", "المكسيك", "Mexico", "+52"),
        ("MY", "ماليزيا", "Malaysia", "+60"),
        ("MZ", "موزمبيق", "Mozambique", "+258"),
        ("NA", "ناميبيا", "Namibia", "+264"),
        ("NC", "كاليدونيا الجديدة", "New Caledonia", "+687"),
        ("NE", "النيجر", "Niger", "+227"),
        ("NF", "جزيرة نورفولك", "Norfolk Island", "+672"),
        ("NG", "نيجيريا", "Nigeria", "+234"),
        ("NI", "نيكاراغوا", "Nicaragua", "+505"),
        ("NL", "هولندا", "Netherlands", "+31"),
        ("NO", "النرويج", "Norway", "+47"),
        ("NP", "نيبال", "Nepal", "+977"),
        ("NR", "ناورو", "Nauru", "+674"),
        ("NU", "نيوي", "Niue", "+683"),
        ("NZ", "نيوزيلندا", "New Zealand", "+64"),
        ("OM", "عُمان", "Oman", "+968"),
        ("PA", "بنما", "Panama", "+507"),
        ("PE", "بيرو", "Peru", "+51"),
        ("PF", "بولينيزيا الفرنسية", "French Polynesia", "+689"),
        ("PG", "بابوا غينيا الجديدة", "Papua New Guinea", "+675"),
        ("PH", "الفلبين", "Philippines", "+63"),
        ("PK", "باكستان", "Pakistan", "+92"),
        ("PL", "بولندا", "Poland", "+48"),
        ("PM", "سان بيير ومكويلون", "St. Pierre & Miquelon", "+508"),
        ("PR", "بورتوريكو", "Puerto Rico", "+1787"),
        ("PS", "فلسطين", "Palestine", "+970"),
        ("PT", "البرتغال", "Portugal", "+351"),
        ("PW", "بالاو", "Palau", "+680"),
        ("PY", "باراغواي", "Paraguay", "+595"),
        ("QA", "قطر", "Qatar", "+974"),
        ("RE", "روينيون", "Réunion", "+262"),
        ("RO", "رومانيا", "Romania", "+40"),
        ("RS", "صربيا", "Serbia", "+381"),
        ("RU", "روسيا", "Russia", "+7"),
        ("RW", "رواندا", "Rwanda", "+250"),
        ("SA", "السعودية", "Saudi Arabia", "+966"),
        ("SB", "جزر سليمان", "Solomon Islands", "+677"),
        ("SC", "سيشل", "Seychelles", "+248"),
        ("SD", "السودان", "Sudan", "+249"),
        ("SE", "السويد", "Sweden", "+46"),
        ("SG", "سنغافورة", "Singapore", "+65"),
        ("SH", "سانت هيلينا", "St. Helena", "+290"),
        ("SI", "سلوفينيا", "Slovenia", "+386"),
        ("SJ", "سفالبارد وجان ماين", "Svalbard & Jan Mayen", "+47"),
        ("SK", "سلوفاكيا", "Slovakia", "+421"),
        ("SL", "سيراليون", "Sierra Leone", "+232"),
        ("SM", "سان مارينو", "San Marino", "+378"),
        ("SN", "السنغال", "Senegal", "+221"),
        ("SO", "الصومال", "Somalia", "+252"),
        ("SR", "سورينام", "Suriname", "+597"),
        ("SS", "جنوب السودان", "South Sudan", "+211"),
        ("ST", "ساو تومي وبرينسيبي", "São Tomé & Príncipe", "+239"),
        ("SV", "السلفادور", "El Salvador", "+503"),
        ("SX", "سانت مارتن", "Sint Maarten", "+1721"),
        ("SY", "سوريا", "Syria", "+963"),
        ("SZ", "إسواتيني", "Eswatini", "+268"),
        ("TC", "جزر توركس وكايكوس", "Turks & Caicos Islands", "+1649"),
        ("TD", "تشاد", "Chad", "+235"),
        ("TG", "توغو", "Togo", "+228"),
        ("TH", "تايلاند", "Thailand", "+66"),
        ("TJ", "طاجيكستان", "Tajikistan", "+992"),
        ("TK", "توكيلاو", "Tokelau", "+690"),
        ("TL", "تيمور - ليشتي", "Timor-Leste", "+670"),
        ("TM", "تركمانستان", "Turkmenistan", "+993"),
        ("TN", "تونس", "Tunisia", "+216"),
        ("TO", "تونغا", "Tonga", "+676"),
        ("TR", "تركيا", "Türkiye", "+90"),
        ("TT", "ترينيداد وتوباغو", "Trinidad & Tobago", "+1868"),
        ("TV", "توفالو", "Tuvalu", "+688"),
        ("TW", "تايوان", "Taiwan", "+886"),
        ("TZ", "تنزانيا", "Tanzania", "+255"),
        ("UA", "أوكرانيا", "Ukraine", "+380"),
        ("UG", "أوغندا", "Uganda", "+256"),
        ("US", "الولايات المتحدة", "United States", "+1"),
        ("UY", "أورغواي", "Uruguay", "+598"),
        ("UZ", "أوزبكستان", "Uzbekistan", "+998"),
        ("VA", "الفاتيكان", "Vatican City", "+39"),
        ("VC", "سانت فنسنت وجزر غرينادين", "St. Vincent & Grenadines", "+1784"),
        ("VE", "فنزويلا", "Venezuela", "+58"),
        ("VG", "جزر فيرجن البريطانية", "British Virgin Islands", "+1284"),
        ("VN", "فيتنام", "Vietnam", "+84"),
        ("VU", "فانواتو", "Vanuatu", "+678"),
        ("WF", "جزر والس وفوتونا", "Wallis & Futuna", "+681"),
        ("WS", "ساموا", "Samoa", "+685"),
        ("XK", "كوسوفو", "Kosovo", "+383"),
        ("YE", "اليمن", "Yemen", "+967"),
        ("YT", "مايوت", "Mayotte", "+262"),
        ("ZA", "جنوب أفريقيا", "South Africa", "+27"),
        ("ZM", "زامبيا", "Zambia", "+260"),
        ("ZW", "زيمبابوي", "Zimbabwe", "+263")
    ];
}
